/**
 * seedDiseases.js
 *
 * Seeds the `diseases` collection with a standard disease/diagnosis list.
 * Used to populate the Diagnosis dropdown in the Prescription form.
 *
 * The function skips if the collection is already populated.
 * Pass `force = true` to wipe and re-seed.
 */

import { collection, addDoc, getDocs, deleteDoc, serverTimestamp } from 'firebase/firestore';
import { db } from './config';

const DISEASES = [
  'Abortion (incomplete)',
  'Acromegaly',
  "Addison's disease",
  'Adrenocortical insufficiency',
  'Allergy (ophthalmic)',
  'Allergy prophylaxis',
  'Allergy treatment',
  'Amenorrhoea',
  'Amoebiasis',
  'Anaemia',
  'Anaphylaxis',
  'Angina pectoris',
  'Angioneurotic oedema',
  'Ankylosing spondylitis',
  'Anorexia',
  'Anxiety states',
  'Appetite (loss/suppression)',
  'Arrhythmias',
  'Arteriosclerosis',
  'Arthritic disorders',
  'Asthma (allergic)',
  "Athlete's foot",
  'Barbiturate poisoning',
  'Behavioural disorders',
  'Belching/regurgitation',
  'Biliary disorders',
  'Bronchitis',
  'Bronchial congestion',
  'Bronchiectasis',
  'Bronchospasm',
  "Burger's disease",
  'Calcium deficiency',
  'Cancer',
  'Candidiasis (oral, skin, vaginal)',
  'Carcinoma (prostate)',
  'Cardiac failure',
  'Cardiac arrhythmias',
  'Cardiac sphincter spasm',
  'Cerebrovascular insufficiency',
  'Cheyne-Stokes breathing',
  'Cholelithiasis',
  'Chronic alcoholism',
  'Circulation (cerebral/peripheral)',
  'Claudication',
  'Climacteric symptoms',
  'Colitis',
  'Colitis (ulcerative)',
  'Collagen disorders',
  'Colorectal carcinoma',
  'Common cold',
  'Conjunctivitis (allergic/infective)',
  'Constipation',
  'Contraception',
  'Convulsions',
  'Coronary insufficiency',
  'Thrombosis',
  'Cough',
  'Cretinism',
  "Crohn's disease",
  'Cryptitis',
  'Cryptorchidism',
  'Cystic fibrosis',
  'Cystinuria',
  'Cystitis',
  'Dandruff',
  'Debility',
  'Dengue',
  'Diphtheria',
  'Vitamin deficiency',
  'Folic acid deficiency',
  'Dehydration',
  'Depression',
  'Dermatitis (fungal/infective/seborrhoeic)',
  'Diabetes insipidus',
  'Diabetes mellitus',
  'Diarrhoea',
  'Duodenal ulcer',
  'Dysentery (bacterial/amoebic)',
  'Dysmenorrhoea',
  'Dyspepsia (acidic/enzyme deficiency)',
  'Earache',
  'Eczema',
  'Embolism',
  'Emergency medication',
  'Emotional disturbances',
  'Emphysema',
  'Endometriosis',
  'Eunuchoidism',
  'Enuresis',
  'Eosinophilia',
  'Epilepsy',
  'Extrapyramidal disorders',
  'Fever',
  'Fibrositis',
  'Filariasis',
  'Flatulence',
  'Food poisoning',
  'Fractures (support)',
  'Fungal skin infections',
  'Gas Gangrene',
  'Gastric ulcer',
  'Gastritis',
  'Gastro-enteritis',
  'Gastrointestinal spasm',
  'Giardiasis',
  'Gingivitis',
  'Glaucoma',
  'Gonorrhoea',
  'Gout',
  'Grand mal epilepsy',
  'H. pylori eradication',
  'Haemophilus B',
  'Haemorrhage (postpartum)',
  'Haemorrhoids',
  'Hay fever',
  'Headache (vascular)',
  'Heartburn',
  'Hepatitis A',
  'Hepatitis B',
  'Hepatitis (amoebic/infective/B)',
  'Hepato-biliary disorders',
  'Herpes (ocular/genital)',
  'Hiatus hernia',
  "Hodgkin's disease",
  'Human Papillomavirus',
  'Hyperacidity',
  'Hypercholesterolaemia',
  'Hyperemesis gravidarum',
  'Hyperglycaemia',
  'Hyperthyroidism',
  'Hyperuricaemia',
  'Hypoglycaemia',
  'Hypogonadism',
  'Hypokalaemia',
  'Hypoparathyroidism',
  'Hypotension',
  'Hypothyroidism',
  'Immunisation',
  'Impetigo',
  'Impotence',
  'Infections (bacterial/fungal/systemic)',
  'Inflammatory conditions',
  'Influenza',
  'Insomnia',
  'Intermittent claudication',
  'Iritis',
  'Ischaemia',
  'Jaundice',
  'Kala-azar',
  'Keratitis',
  'Labour (premature)',
  'Labyrinthitis',
  'Lactation suppression',
  'Leprosy',
  'Leukaemia',
  'Libido loss',
  'Lice',
  'Low back syndrome',
  'Lupus erythematosus',
  'Malaria',
  'Malignant disease',
  'Measles',
  'Meningococcal',
  'Mastoiditis',
  "Meniere's syndrome",
  'Menorrhagia',
  'Menstrual disorders',
  'Metal poisoning',
  'Methotrexate overdose',
  'Migraine',
  'Moniliasis',
  'Motion sickness',
  'Myasthenia gravis',
  'Myocardial infarction',
  'Myxoedema',
  'Nappy rash',
  'Nausea (pregnancy)',
  'Neuralgia',
  'Neurasthenia',
  'Neuritis',
  'Neurosis',
  'Obesity',
  'Oedema',
  'Oligomenorrhoea',
  'Osteoarthritis',
  'Osteoporosis',
  'Otitis media',
  'Ovulation inhibition',
  "Paget's disease",
  'Pain (general/muscular)',
  'Pancreatitis',
  'Paralysis',
  'Parkinsonism',
  'Peptic ulcer',
  'Pigmentation',
  'Pneumococcal',
  'Pneumonia',
  'Polio',
  'Poisoning',
  'Pregnancy prevention',
  'Premenstrual syndrome',
  'Proctitis',
  'Prostate cancer',
  'Prostatic hypertrophy',
  'Pruritus',
  'Psoriasis',
  'Rabies',
  'Rotavirus',
  'Rubella',
  'Psychomotor seizures',
  'Psychosis',
  'Puberty (delayed)',
  'Pyelitis',
  'Pyorrhoea',
  "Raynaud's disease",
  'Renal failure',
  'Respiratory depression',
  'Rheumatic disorders',
  'Rhinitis (allergic)',
  'Rickets',
  'Ringworm',
  'Roundworm',
  'Scabies',
  'Schizophrenia',
  'Sciatica',
  'Seasonal allergic conjunctivitis',
  'Seborrhoea',
  'Septicaemia',
  'Shock (anaphylactic)',
  'Sinusitis',
  'Skin disorders',
  'Spasm',
  'Spasticity',
  'Status asthmaticus',
  'Status epilepticus',
  'Steatorrhoea',
  'Sterility',
  'Stress',
  'Syphilis',
  'Systemic mycoses',
  'Tapeworm',
  'Testes (undescended)',
  'Tetanus',
  'Thalassemia',
  'Threadworm',
  'Throat (sore)',
  'Thrombosis',
  'Thrush',
  'Thyrotoxicosis',
  'Tinea',
  'Tinnitus',
  'Tonsillitis',
  'Trachoma',
  'Tremor',
  'Trichomoniasis',
  'Thrombophlebitis',
  'Tuberculosis',
  'Typhoid',
  'Ulcer',
  'Urethritis',
  'Urinary retention',
  'Urinary tract infection',
  'Urolithiasis',
  'Urticaria',
  'Vaccination',
  'Vaginitis',
  'Varicose ulcers/veins',
  'Vertigo',
  "Vincent's infection",
  'Vitamin deficiencies',
  'Vitiligo',
  'Vomiting',
  'Wasting disease',
  'Yellow Fever',
  "Wilson's disease",
  'Worms',
];

export async function seedDiseases(force = false) {
  const col = collection(db, 'diseases');

  if (!force) {
    const existing = await getDocs(col);
    if (!existing.empty) {
      return { skipped: true, count: existing.size };
    }
  } else {
    // Wipe existing docs
    const existing = await getDocs(col);
    await Promise.all(existing.docs.map(d => deleteDoc(d.ref)));
  }

  await Promise.all(
    DISEASES.map(name =>
      addDoc(col, { name, createdAt: serverTimestamp() })
    )
  );

  return { skipped: false, count: DISEASES.length };
}
